// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYjeGkKWSsQoFWzqBRJBy5YcHfkYJYdG4',
    appId: '1:796391861849:web:a4e72b54bfe1ecbbc40b48',
    messagingSenderId: '796391861849',
    projectId: 'sih26-ca0a1',
    authDomain: 'sih26-ca0a1.firebaseapp.com',
    storageBucket: 'sih26-ca0a1.firebasestorage.app',
    measurementId: 'G-KMPBN1GKP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ8K4pa8o86JDXBTwNFRwcXrT5Knc4LAA',
    appId: '1:796391861849:android:8693a76e2575d0e8c40b48',
    messagingSenderId: '796391861849',
    projectId: 'sih26-ca0a1',
    storageBucket: 'sih26-ca0a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtDZG9WUfqCDE3h7-X1CikJwKyWkEPqfw',
    appId: '1:796391861849:ios:d8a0788bc6f91794c40b48',
    messagingSenderId: '796391861849',
    projectId: 'sih26-ca0a1',
    storageBucket: 'sih26-ca0a1.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtDZG9WUfqCDE3h7-X1CikJwKyWkEPqfw',
    appId: '1:796391861849:ios:d8a0788bc6f91794c40b48',
    messagingSenderId: '796391861849',
    projectId: 'sih26-ca0a1',
    storageBucket: 'sih26-ca0a1.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYjeGkKWSsQoFWzqBRJBy5YcHfkYJYdG4',
    appId: '1:796391861849:web:c29c0e6a8dc1f794c40b48',
    messagingSenderId: '796391861849',
    projectId: 'sih26-ca0a1',
    authDomain: 'sih26-ca0a1.firebaseapp.com',
    storageBucket: 'sih26-ca0a1.firebasestorage.app',
    measurementId: 'G-XXBRHTQ3YR',
  );
}
